from datetime import date
from data_sheet_create_0_1 import PromotionActivity, session

def insert_simulated_promotions():
    promotions = [
        # 2023
        {
            "campaign_name": "2023 New Year Spectacle Sale",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 1, 1),
            "end_date": date(2023, 1, 31),
            "discount_type": "Percentage",
            "discount_value": 0.20,
            "min_purchase_amount": 300.0,
            "expected_sales_lift": 1.12,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Valentine’s Day Lens Event",
            "campaign_type": "Holiday",
            "target_audience": "Existing Customers",
            "region": "United States",
            "start_date": date(2023, 2, 1),
            "end_date": date(2023, 2, 28),
            "discount_type": "Fixed Amount",
            "discount_value": 50.0,
            "min_purchase_amount": 500.0,
            "expected_sales_lift": 1.18,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Spring Sale",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 3, 1),
            "end_date": date(2023, 4, 30),
            "discount_type": "Percentage",
            "discount_value": 0.18,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.10,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Easter Eye Care Gift",
            "campaign_type": "Member",
            "target_audience": "Existing Customers",
            "region": "United States",
            "start_date": date(2023, 4, 1),
            "end_date": date(2023, 4, 30),
            "discount_type": "Free Gift",
            "discount_value": 0.0,
            "min_purchase_amount": 600.0,
            "expected_sales_lift": 1.08,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Mother’s Day Special",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 5, 1),
            "end_date": date(2023, 5, 31),
            "discount_type": "Percentage",
            "discount_value": 0.22,
            "min_purchase_amount": 400.0,
            "expected_sales_lift": 1.16,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Summer Sunglass Sale",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 6, 1),
            "end_date": date(2023, 6, 30),
            "discount_type": "Percentage",
            "discount_value": 0.15,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.09,
            "status": "completed"
        },
        {
            "campaign_name": "2023 July 4 Independence Event",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 7, 1),
            "end_date": date(2023, 7, 31),
            "discount_type": "Fixed Amount",
            "discount_value": 80.0,
            "min_purchase_amount": 500.0,
            "expected_sales_lift": 1.13,
            "status": "completed"
        },
        {
            "campaign_name": "2023 August Summer Clearance",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 8, 1),
            "end_date": date(2023, 8, 31),
            "discount_type": "Percentage",
            "discount_value": 0.20,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.11,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Back to School",
            "campaign_type": "Seasonal",
            "target_audience": "New Customers",
            "region": "United States",
            "start_date": date(2023, 9, 1),
            "end_date": date(2023, 9, 30),
            "discount_type": "Buy One Get One",
            "discount_value": 0.0,
            "min_purchase_amount": 300.0,
            "expected_sales_lift": 1.20,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Halloween Frame Treat",
            "campaign_type": "Holiday",
            "target_audience": "VIP Customers",
            "region": "United States",
            "start_date": date(2023, 10, 1),
            "end_date": date(2023, 10, 31),
            "discount_type": "Percentage",
            "discount_value": 0.18,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.07,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Black Friday",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 11, 1),
            "end_date": date(2023, 11, 30),
            "discount_type": "Fixed Amount",
            "discount_value": 100.0,
            "min_purchase_amount": 600.0,
            "expected_sales_lift": 1.28,
            "status": "completed"
        },
        {
            "campaign_name": "2023 Christmas Gift Sale",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2023, 12, 1),
            "end_date": date(2023, 12, 31),
            "discount_type": "Percentage",
            "discount_value": 0.25,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.22,
            "status": "completed"
        },

        # 2024
        {
            "campaign_name": "2024 New Year Celebration",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 1, 1),
            "end_date": date(2024, 1, 31),
            "discount_type": "Percentage",
            "discount_value": 0.22,
            "min_purchase_amount": 300.0,
            "expected_sales_lift": 1.18,
            "status": "active"
        },
        {
            "campaign_name": "2024 Valentine’s Day Lens Event",
            "campaign_type": "Holiday",
            "target_audience": "Existing Customers",
            "region": "United States",
            "start_date": date(2024, 2, 1),
            "end_date": date(2024, 2, 29),
            "discount_type": "Fixed Amount",
            "discount_value": 60.0,
            "min_purchase_amount": 500.0,
            "expected_sales_lift": 1.20,
            "status": "active"
        },
        {
            "campaign_name": "2024 Spring Sale",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 3, 1),
            "end_date": date(2024, 3, 31),
            "discount_type": "Percentage",
            "discount_value": 0.20,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.14,
            "status": "active"
        },
        {
            "campaign_name": "2024 Easter Eye Care Gift",
            "campaign_type": "Member",
            "target_audience": "Existing Customers",
            "region": "United States",
            "start_date": date(2024, 4, 1),
            "end_date": date(2024, 4, 30),
            "discount_type": "Free Gift",
            "discount_value": 0.0,
            "min_purchase_amount": 500.0,
            "expected_sales_lift": 1.09,
            "status": "active"
        },
        {
            "campaign_name": "2024 Mother’s Day Special",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 5, 1),
            "end_date": date(2024, 5, 31),
            "discount_type": "Percentage",
            "discount_value": 0.24,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.19,
            "status": "active"
        },
        {
            "campaign_name": "2024 Summer Shield Sale",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 6, 1),
            "end_date": date(2024, 6, 30),
            "discount_type": "Percentage",
            "discount_value": 0.18,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.12,
            "status": "active"
        },
        {
            "campaign_name": "2024 July 4 Independence Sale",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 7, 1),
            "end_date": date(2024, 7, 31),
            "discount_type": "Fixed Amount",
            "discount_value": 80.0,
            "min_purchase_amount": 500.0,
            "expected_sales_lift": 1.15,
            "status": "active"
        },
        {
            "campaign_name": "2024 August Summer Clearance",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 8, 1),
            "end_date": date(2024, 8, 31),
            "discount_type": "Percentage",
            "discount_value": 0.22,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.13,
            "status": "active"
        },
        {
            "campaign_name": "2024 Back to School",
            "campaign_type": "Seasonal",
            "target_audience": "New Customers",
            "region": "United States",
            "start_date": date(2024, 9, 1),
            "end_date": date(2024, 9, 30),
            "discount_type": "Buy One Get One",
            "discount_value": 0.0,
            "min_purchase_amount": 300.0,
            "expected_sales_lift": 1.21,
            "status": "active"
        },
        {
            "campaign_name": "2024 Fall Frame Fest",
            "campaign_type": "Seasonal",
            "target_audience": "VIP Customers",
            "region": "United States",
            "start_date": date(2024, 10, 1),
            "end_date": date(2024, 10, 31),
            "discount_type": "Percentage",
            "discount_value": 0.19,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.11,
            "status": "active"
        },
        {
            "campaign_name": "2024 Singles Day Spectacle Event",
            "campaign_type": "Holiday",
            "target_audience": "New Customers",
            "region": "United States",
            "start_date": date(2024, 11, 1),
            "end_date": date(2024, 11, 30),
            "discount_type": "Percentage",
            "discount_value": 0.30,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.35,
            "status": "active"
        },
        {
            "campaign_name": "2024 Black Friday",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 11, 1),
            "end_date": date(2024, 11, 30),
            "discount_type": "Fixed Amount",
            "discount_value": 120.0,
            "min_purchase_amount": 600.0,
            "expected_sales_lift": 1.30,
            "status": "active"
        },
        {
            "campaign_name": "2024 Christmas Gift Sale",
            "campaign_type": "Holiday",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 12, 1),
            "end_date": date(2024, 12, 31),
            "discount_type": "Percentage",
            "discount_value": 0.28,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.25,
            "status": "active"
        },
        {
            "campaign_name": "2024 Year-End Clearance",
            "campaign_type": "Seasonal",
            "target_audience": "All Customers",
            "region": "United States",
            "start_date": date(2024, 12, 26),
            "end_date": date(2024, 12, 31),
            "discount_type": "Percentage",
            "discount_value": 0.35,
            "min_purchase_amount": 0.0,
            "expected_sales_lift": 1.18,
            "status": "active"
        },
        {
            "campaign_name": "2024 Anniversary Member Drive",
            "campaign_type": "Member",
            "target_audience": "VIP Customers",
            "region": "United States",
            "start_date": date(2024, 10, 1),
            "end_date": date(2024, 10, 31),
            "discount_type": "Free Gift",
            "discount_value": 0.0,
            "min_purchase_amount": 400.0,
            "expected_sales_lift": 1.14,
            "status": "active"
        },
    ]

    for p in promotions:
        session.add(PromotionActivity(**p))
    session.commit()
    print(f"Inserted {len(promotions)} promotion activities.")
    
if __name__ == "__main__":
    insert_simulated_promotions()